name: Frontend Tests

on:
  push:
    branches: [main, v1_feature]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run the tests
      - name: Run tests
        run: flutter test